name: "falco-validator"
description: "Validates Falco rules using falco-validator container image"

inputs:
  falco_version:
    description: "Falco version to use for validation (determines container image tag)"
    required: true
    default: "0.43.0"
  rules:
    description: "Space-separated list of rules to validate (mix of artifact names and file paths)"
    required: true
  stable:
    description: "Inject Falco stable ruleset"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "ghcr.io/acidghost/falco-validator:v1.0.0-f${{ inputs.falco_version }}"
  env:
    FALCO_VALIDATOR_RULES: ${{ inputs.rules }}
    FALCO_VALIDATOR_STABLE: ${{ inputs.stable }}
